version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"  # ✅ Match PORT=8000
    environment:
      DB_HOST: db  # ✅ Use service name "db"
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: auth_api
      DB_PORT: 3306
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: auth_api
      MYSQL_ROOT_PASSWORD: root_password 
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
